# Generated by Django 6.0.1 on 2026-01-28 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_is_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='product',
            name='is_handmade',
            field=models.BooleanField(default=False, verbose_name='Ручная работа'),
        ),
        migrations.AddField(
            model_name='product',
            name='material',
            field=models.CharField(blank=True, max_length=100, verbose_name='Материал'),
        ),
        migrations.AddField(
            model_name='product',
            name='package_contents',
            field=models.CharField(blank=True, max_length=200, verbose_name='Комплект'),
        ),
        migrations.AddField(
            model_name='product',
            name='protection',
            field=models.CharField(blank=True, max_length=100, verbose_name='Защита'),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
    ]
